package com.example.structureplugin

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.ui.Messages
import java.io.File

class CreateStructureAction : AnAction("Create Project Structure") {
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val basePath = project.basePath ?: return

        // 🔹 шукаємо найтиповіший MainActivity.kt або будь-який Activity
        val mainFile = File(basePath).walkTopDown().firstOrNull {
            it.isFile && it.extension == "kt" &&
                    (it.name.contains("MainActivity", true) || it.readText().contains("class MainActivity"))
        }

        // 🔹 якщо не знайшли — беремо будь-який .kt у kotlin+java/…/com/…/
        val targetDir = mainFile?.parentFile ?: File(basePath)
            .walkTopDown()
            .firstOrNull { it.isDirectory && it.path.replace("\\", "/").contains("app/src/main/") && it.name == "ui" }
            ?.parentFile
        ?: File(basePath, "app/src/main")

        // 🔹 створюємо структуру поруч із MainActivity
        val folders = listOf(
            "data/repository",
            "data/model",
            "domain/usecase",
            "ui/screens",
            "ui/components"
        )

        for (folder in folders) {
            val dir = File(targetDir, folder)
            if (!dir.exists()) dir.mkdirs()
            val readme = File(dir, "README.md")
            if (!readme.exists()) {
                readme.writeText("# ${folder.substringAfterLast('/')}\n\nAutogenerated folder description.")
            }
        }

        VfsUtil.markDirtyAndRefresh(false, true, true, File(basePath))
        Messages.showInfoMessage(
            project,
            "Folders created inside: ${targetDir.path}",
            "Done"
        )
    }
}
